version: 2.1

jobs:
  deploy:
    docker:
      - image: amazon/aws-cli
    environment:
      AWS_REGION: ap-south-1
    steps:
      - checkout

      - run:
          name: Install Git and Python (for EC2 if needed)
          command: |
            yum install -y git python3 || sudo apt-get install -y git python3

      - run:
          name: Retrieve SSH private key from AWS SSM
          command: |
            aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
            aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
            aws configure set region "$AWS_REGION"
            aws ssm get-parameter \
              --name "circleci-ec2-ssh-key" \
              --with-decryption \
              --query "Parameter.Value" \
              --output text > ec2_key.pem
            chmod 600 ec2_key.pem

      - run:
          name: SSH into EC2 and deploy app
          command: |
            ssh -o StrictHostKeyChecking=no -i ec2_key.pem "$EC2_USER@$EC2_HOST" \<< 'EOF'
              set -e
              mkdir -p /home/ubuntu/app
              cd /home/ubuntu/app

              if [ ! -d .git ]; then
               git clone https://github.com/20481A04K2/circleciawsec2.git .
              else
                git pull
              fi
              if ! command -v python3 &>/dev/null; then
               sudo apt update
               sudo apt install -y python3
              fi

              if ! command -v pip3 &>/dev/null; then
               sudo apt install -y python3-pip
              fi
              pip3 install flask

              # Kill previous app if running
              pkill -f app.py || true

              nohup sudo python3 app.py > app.log 2>&1 &
            EOF

workflows:
  deploy_to_ec2:
    jobs:
      - deploy
