version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/python:3.11  # Use any suitable Python version

    steps:
      - checkout

      - run:
          name: Install AWS CLI & SSH
          command: |
            sudo apt update
            sudo apt install -y awscli openssh-client

      - run:
          name: Fetch private SSH key from AWS SSM
          command: |
            aws ssm get-parameter \
              --name "circleci-ec2-ssh-key" \
              --with-decryption \
              --region "$AWS_REGION" \
              --query "Parameter.Value" \
              --output text > ~/ec2_key.pem
            chmod 600 ~/ec2_key.pem

      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no -i ~/ec2_key.pem "$EC2_USER@$EC2_HOST" << 'EOF'
              cd /home/ec2-user/app
              pip3 install -r requirements.txt
              nohup python3 app.py > app.log 2>&1 &
            EOF

workflows:
  deploy_to_ec2:
    jobs:
      - deploy
