version: 2.1

jobs:
  deploy:
    docker:
      - image: amazon/aws-cli
    environment:
      AWS_REGION: ap-south-1
    steps:
      - checkout

      - run:
          name: Install Git and Python
          command: |
            which git || (yum install -y git || apt-get update && apt-get install -y git)
            which python3 || (yum install -y python3 || apt-get update && apt-get install -y python3)

      - run:
          name: Configure AWS CLI and Retrieve SSH Private Key from SSM
          command: |
            aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
            aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
            aws configure set region "$AWS_REGION"

            aws ssm get-parameter \
              --name "circleci-ec2-ssh-key" \
              --with-decryption \
              --query "Parameter.Value" \
              --output text > ec2_key.pem
            chmod 600 ec2_key.pem

      - run:
          name: SSH into EC2 and Deploy App
          command: |
            ssh -o StrictHostKeyChecking=no -i ec2_key.pem "$EC2_USER@$EC2_HOST" << 'EOF'
              set -e
              APP_DIR="/home/ec2-user/app"
              if [ ! -d "$APP_DIR" ]; then
                mkdir -p "$APP_DIR"
              fi
              cd "$APP_DIR"

              if [ ! -d .git ]; then
                git clone https://github.com/20481A04K2/circleciawsec2.git .
              else
                git pull
              fi

              pip3 install --user -r requirements.txt

              pkill -f app.py || true
              nohup python3 app.py > app.log 2>&1 &
            EOF

workflows:
  deploy_to_ec2:
    jobs:
      - deploy
