version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout

      - run:
          name: Save SSH key
          command: |
            echo "$PEM" > ec2_key.pem
            chmod 400 ec2_key.pem

      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no -i ec2_key.pem "$EC2_USER@$EC2_HOST" '
              mkdir -p /home/ec2-user/app
              cd /home/ec2-user/app
              if [ ! -d .git ]; then
                git clone https://github.com/20481A04K2/circleciawsec2.git .
              else
                git pull
              fi
              pip3 install -r requirements.txt
              nohup python3 app.py > app.log 2>&1 &
            '

workflows:
  deploy_to_ec2:
    jobs:
      - deploy
